[deps]
numpy = ""
qiskit-aer = ""
matplotlib = ""
qutip = ""
rustworkx = ""
opt_einsum = ""
qiskit-ibm-runtime = ""

    [deps.qiskit]
    channel = "conda-forge"

[pip]
mqt-yaqs = ""

    [pip.deps]
    mqt-yaqs = ""
