name = "Yaqs"
uuid = "49393c84-1018-4446-9392-116eb502ef7e"
authors = ["Maximilian Frohlich"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
